name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Marco-cefetmg/android_kernel_samsung_exynos7870
          kernel-branch: master
          config: exynos7870-gtanotexllte_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          android-version: 10
          extra-cmd: ANDROID_MAJOR_VERSION=o
